### ISSUE TITLE
Package README 

### ISSUE THREAD

**Issue by Airblader** [TNG/ngx-structurals#18]
The README is currently on root level so Github can read it, but for npm we need to copy it into the dist folder before publishing.

**Comment by Airblader** [comment]
Also the link to Github is missing, we need to make sure this is in the packaged package.json.

**Comment by theone1984** [comment]
Do we also need to copy the license, etc.?

**Comment by Airblader** [comment]
Good point, yes, we should copy the license as well.

**Comment by Airblader** [comment]
Also released as 1.0.1 so everything is on npm now.
