### ISSUE TITLE
Add support for Angular 12

### ISSUE THREAD

**Issue by snebjorn** [TNG/ngx-structurals#56]
https://github.com/TNG/ngx-structurals/blob/8bc6f25fbd45c440a4050a41bfffd280d356ff49/projects/ngx-structurals/package.json#L19-L20

Angular 12 appears to work. Can it get added to the supported version list?

**Comment by Airblader** [comment]
Certainly! I've opened the PR. Will release a new version as soon as possible.

**Comment by Airblader** [comment]
ngx-structurals@1.2.2 is now released
